// This file is @generated by scripts/generate-schemas.mjs. DO NOT EDIT.
// canonical schema: schemas/studio.shared.v1alpha1.schema.json
// schema sha256: bb7bc4df1a1f684337275d638887613b3421cff17e90d63845e21c45ec18b3fd
// generator sha256: bd3ecf4aed3c2c1f233b3b65e9e55302c33d9931527b50849f668d1858dba375

use std::collections::BTreeMap;

use serde::{Deserialize, Serialize};
use serde_json::Value;

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct AuditEnvelope {
    pub action: String,
    pub actor_principal_id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub details: Option<BTreeMap<String, Value>>,
    pub fleet_id: String,
    pub id: String,
    pub occurred_at: String,
    pub outcome: String,
    pub redacted_digest: String,
    pub request_id: String,
    pub target_resource_ids: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct CapabilityDeclaration {
    pub id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub parameters_schema: Option<BTreeMap<String, Value>>,
    pub required: bool,
    pub version: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct CompatibilityDecision {
    pub accepted_capabilities: Vec<String>,
    pub outcome: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    pub selected_contracts: Vec<SelectedSchemaProfile>,
    pub side_effect_permitted: bool,
    pub unavailable_capabilities: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct CompatibilityPeer {
    pub capabilities: Vec<String>,
    pub contracts: Vec<SchemaProfile>,
    pub extensions: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct CompatibilityRequest {
    pub contracts: Vec<SchemaProfile>,
    pub optional_capabilities: Vec<String>,
    pub required_capabilities: Vec<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub required_extensions: Option<Vec<String>>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct CoreErrorEnvelope {
    pub category: String,
    pub code: String,
    pub message: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub operation_id: Option<String>,
    pub request_id: String,
    pub retryable: bool,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct CoreEventEnvelope {
    pub command_kind: String,
    pub event_type: String,
    pub operation_id: String,
    pub outcome: String,
    pub request_id: String,
    pub sequence: i64,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ExtensionEnvelope {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub payload: Option<BTreeMap<String, Value>>,
    pub schema_version: i64,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct FleetIdentity {
    pub display_name: String,
    pub id: String,
    pub revision: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct Grant {
    pub actions: Vec<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub conditions: Option<BTreeMap<String, Value>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<String>,
    pub fleet_id: String,
    pub id: String,
    pub issuer_principal_id: String,
    pub principal_id: String,
    pub resource_selector: ResourceSelector,
    pub revision: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct InstanceDescriptor {
    pub discovery_url: String,
    pub display_name: String,
    pub fleet_id: String,
    pub id: String,
    pub status: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct MemoryReference {
    pub fleet_id: String,
    pub id: String,
    pub provenance: String,
    pub provider_id: String,
    pub provider_reference: String,
    pub retention: String,
    pub revision: String,
    pub scope: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub visibility: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct NetworkPermission {
    pub allow: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct PackageIntegrity {
    pub digest: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub signature: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct PluginCompatibility {
    pub contracts: Vec<SchemaProfile>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub optional_capabilities: Option<Vec<String>>,
    pub required_capabilities: Vec<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub required_extensions: Option<Vec<String>>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct PluginContributions {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub memory_providers: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub resource_types: Option<Vec<String>>,
    pub tools: Vec<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub workflows: Option<Vec<String>>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct PluginManifest {
    pub compatibility: PluginCompatibility,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub configuration_schema: Option<BTreeMap<String, Value>>,
    pub contributes: PluginContributions,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub extensions: Option<BTreeMap<String, ExtensionEnvelope>>,
    pub id: String,
    pub migration: PluginMigrationCompatibility,
    pub name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub package: Option<PackageIntegrity>,
    pub permissions: PluginPermissions,
    pub platforms: Vec<String>,
    pub resource_limits: ResourceLimits,
    pub runtime: PluginRuntime,
    pub schema_version: String,
    pub version: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct PluginMigrationCompatibility {
    pub supported_from_schema_versions: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct PluginPermissions {
    pub network: NetworkPermission,
    pub resources: ResourcePermission,
    pub secrets: SecretPermission,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct PluginRuntime {
    pub entrypoint: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub health: Option<RuntimeHealth>,
    pub placement: String,
    pub transport: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct Principal {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub device_id: Option<String>,
    pub display_name: String,
    pub fleet_id: String,
    pub id: String,
    pub kind: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ResourceDescriptor {
    pub actions: Vec<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub attributes: Option<BTreeMap<String, Value>>,
    pub fleet_id: String,
    pub id: String,
    pub owner_principal_id: String,
    pub revision: String,
    #[serde(rename = "type")]
    pub r#type: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ResourceLimits {
    pub cpu_millis: i64,
    pub max_duration_seconds: i64,
    pub max_result_bytes: i64,
    pub memory_mi_b: i64,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ResourcePermission {
    pub read: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ResourceSelector {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub attributes: Option<BTreeMap<String, Value>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub resource_ids: Option<Vec<String>>,
    pub resource_type: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct RuntimeHealth {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub endpoint: Option<String>,
    pub interval_seconds: i64,
    pub kind: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct SchemaProfile {
    pub family: String,
    pub major: i64,
    pub max_minor: i64,
    pub min_minor: i64,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct SecretPermission {
    #[serde(rename = "use")]
    pub r#use: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct SelectedSchemaProfile {
    pub family: String,
    pub major: i64,
    pub minor: i64,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct SharedContractDocument {
    pub audit_envelope: AuditEnvelope,
    pub capabilities: Vec<CapabilityDeclaration>,
    pub fleet: FleetIdentity,
    pub grants: Vec<Grant>,
    pub instance: InstanceDescriptor,
    pub memory_references: Vec<MemoryReference>,
    pub plugin_manifest: PluginManifest,
    pub principals: Vec<Principal>,
    pub resources: Vec<ResourceDescriptor>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct WorkspaceBootstrapCommand {
    pub kind: String,
    pub request_id: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct WorkspaceBootstrapPayload {
    pub protocol_version: i64,
    pub status: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct WorkspaceBootstrapResult {
    pub events: Vec<CoreEventEnvelope>,
    pub operation_id: String,
    pub request_id: String,
    pub workspace_bootstrap: WorkspaceBootstrapPayload,
}
