#!/usr/bin/env node

import { createHash } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const generatorPath = fileURLToPath(import.meta.url);
const repositoryRoot = resolve(dirname(generatorPath), "..");
const schemaPath = resolve(
  repositoryRoot,
  "schemas/studio.shared.v1alpha1.schema.json",
);
const outputs = {
  rust: resolve(repositoryRoot, "crates/studio-protocol/src/generated.rs"),
  typescript: resolve(
    repositoryRoot,
    "schemas/generated/typescript/studio-protocol.ts",
  ),
  typescriptSchema: resolve(
    repositoryRoot,
    "schemas/generated/typescript/schema.ts",
  ),
};

const argumentsAfterNode = process.argv.slice(2);
if (
  argumentsAfterNode.length > 1 ||
  (argumentsAfterNode.length === 1 && argumentsAfterNode[0] !== "--check")
) {
  process.stderr.write("Usage: node scripts/generate-schemas.mjs [--check]\n");
  process.exit(2);
}

const checkOnly = argumentsAfterNode[0] === "--check";
const schemaText = readFileSync(schemaPath, "utf8");
const schema = JSON.parse(schemaText);
assertSupportedSchema(schema);
const schemaHash = sha256(schemaText);
const generatorHash = sha256(readFileSync(generatorPath, "utf8"));
const definitions = Object.entries(schema.$defs).sort(([left], [right]) =>
  compareText(left, right),
);

const generatedHeader = (commentPrefix) =>
  [
    `${commentPrefix} This file is @generated by scripts/generate-schemas.mjs. DO NOT EDIT.`,
    `${commentPrefix} canonical schema: schemas/studio.shared.v1alpha1.schema.json`,
    `${commentPrefix} schema sha256: ${schemaHash}`,
    `${commentPrefix} generator sha256: ${generatorHash}`,
    "",
  ].join("\n");

const rustReservedWords = new Set([
  "as",
  "async",
  "await",
  "break",
  "const",
  "continue",
  "crate",
  "dyn",
  "else",
  "enum",
  "extern",
  "false",
  "fn",
  "for",
  "if",
  "impl",
  "in",
  "let",
  "loop",
  "match",
  "mod",
  "move",
  "mut",
  "pub",
  "ref",
  "return",
  "self",
  "Self",
  "static",
  "struct",
  "super",
  "trait",
  "true",
  "type",
  "unsafe",
  "use",
  "where",
  "while",
]);

function sha256(value) {
  return createHash("sha256").update(value).digest("hex");
}

function compareText(left, right) {
  if (left < right) {
    return -1;
  }
  if (left > right) {
    return 1;
  }
  return 0;
}

function assertSupportedSchema(source) {
  if (!isObject(source)) {
    throw new Error("Canonical schema source must be an object.");
  }

  const allowedRootKeywords = new Set([
    "$schema",
    "$id",
    "title",
    "description",
    "x-openab-contract-family",
    "x-openab-schema-version",
    "x-openab-migrations",
    "$defs",
  ]);
  assertOnlyKeys(source, allowedRootKeywords, "#");

  if (!isObject(source.$defs)) {
    throw new Error("Canonical schema source must declare object $defs.");
  }
  for (const [name, definition] of Object.entries(source.$defs)) {
    assertSchemaNode(definition, `#/$defs/${name}`);
  }

  if (!Array.isArray(source["x-openab-migrations"])) {
    throw new Error(
      "Canonical schema source must declare x-openab-migrations as an array.",
    );
  }
  for (const [index, migration] of source["x-openab-migrations"].entries()) {
    if (!isObject(migration)) {
      throw new Error(`Migration #${index} must be an object.`);
    }
    assertOnlyKeys(
      migration,
      new Set([
        "id",
        "definition",
        "fromSchemaVersion",
        "toSchemaVersion",
        "rename",
      ]),
      `#/x-openab-migrations/${index}`,
    );
    if (!isObject(migration.rename)) {
      throw new Error(`Migration #${index} must declare an object rename map.`);
    }
    if (
      !Object.values(migration.rename).every(
        (target) => typeof target === "string",
      )
    ) {
      throw new Error(`Migration #${index} rename targets must be strings.`);
    }
  }
}

function assertSchemaNode(node, path) {
  if (!isObject(node)) {
    throw new Error(`Schema node ${path} must be an object.`);
  }

  const allowedNodeKeywords = new Set([
    "$ref",
    "type",
    "additionalProperties",
    "required",
    "properties",
    "items",
    "enum",
    "const",
    "minLength",
    "minimum",
    "maximum",
    "minItems",
    "propertyNames",
  ]);
  assertOnlyKeys(node, allowedNodeKeywords, path);

  if (node.$ref !== undefined) {
    if (
      typeof node.$ref !== "string" ||
      !node.$ref.startsWith("#/$defs/") ||
      Object.keys(node).length !== 1
    ) {
      throw new Error(
        `Schema reference ${path}/$ref must be an isolated local definition reference.`,
      );
    }
    return;
  }
  if (
    node.type !== undefined &&
    !["array", "boolean", "integer", "number", "object", "string"].includes(
      node.type,
    )
  ) {
    throw new Error(`Schema node ${path} uses an unsupported type.`);
  }
  if (
    node.required !== undefined &&
    (!Array.isArray(node.required) ||
      !node.required.every((field) => typeof field === "string"))
  ) {
    throw new Error(
      `Schema node ${path}/required must be an array of strings.`,
    );
  }
  if (node.enum !== undefined && !Array.isArray(node.enum)) {
    throw new Error(`Schema node ${path}/enum must be an array.`);
  }
  for (const keyword of ["minLength", "minimum", "maximum", "minItems"]) {
    if (node[keyword] !== undefined && typeof node[keyword] !== "number") {
      throw new Error(`Schema node ${path}/${keyword} must be a number.`);
    }
  }

  if (node.properties !== undefined) {
    if (!isObject(node.properties)) {
      throw new Error(`Schema node ${path}/properties must be an object.`);
    }
    for (const [property, child] of Object.entries(node.properties)) {
      assertSchemaNode(child, `${path}/properties/${property}`);
    }
  }
  if (node.items !== undefined) {
    assertSchemaNode(node.items, `${path}/items`);
  }
  if (isObject(node.additionalProperties)) {
    assertSchemaNode(node.additionalProperties, `${path}/additionalProperties`);
  } else if (
    node.additionalProperties !== undefined &&
    typeof node.additionalProperties !== "boolean"
  ) {
    throw new Error(
      `Schema node ${path}/additionalProperties must be boolean or schema.`,
    );
  }
  if (node.propertyNames !== undefined) {
    if (!isObject(node.propertyNames)) {
      throw new Error(`Schema node ${path}/propertyNames must be an object.`);
    }
    assertOnlyKeys(
      node.propertyNames,
      new Set(["pattern"]),
      `${path}/propertyNames`,
    );
    if (typeof node.propertyNames.pattern !== "string") {
      throw new Error(
        `Schema node ${path}/propertyNames/pattern must be a string.`,
      );
    }
  }
}

function assertOnlyKeys(value, allowedKeys, path) {
  for (const key of Object.keys(value)) {
    if (!allowedKeys.has(key)) {
      throw new Error(`Unsupported schema keyword ${path}/${key}.`);
    }
  }
}

function isObject(value) {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function snakeCase(value) {
  return value
    .replace(/([a-z0-9])([A-Z])/gu, "$1_$2")
    .replace(/[^a-zA-Z0-9]+/gu, "_")
    .replace(/^_+|_+$/gu, "")
    .toLowerCase();
}

function rustFieldName(propertyName) {
  const name = snakeCase(propertyName);
  return rustReservedWords.has(name) ? `r#${name}` : name;
}

function rustType(node) {
  if (node.$ref) {
    return node.$ref.replace("#/$defs/", "");
  }

  if (node.type === "array") {
    return `Vec<${rustType(node.items)}>`;
  }

  if (node.type === "object") {
    if (node.additionalProperties === true) {
      return "BTreeMap<String, Value>";
    }

    if (typeof node.additionalProperties === "object") {
      return `BTreeMap<String, ${rustType(node.additionalProperties)}>`;
    }
  }

  switch (node.type) {
    case "boolean":
      return "bool";
    case "integer":
      return "i64";
    case "number":
      return "f64";
    case "string":
      return "String";
    default:
      throw new Error(`Unsupported Rust schema node: ${JSON.stringify(node)}`);
  }
}

function typescriptType(node) {
  if (node.$ref) {
    return node.$ref.replace("#/$defs/", "");
  }

  if (node.type === "array") {
    return `Array<${typescriptType(node.items)}>`;
  }

  if (node.type === "object") {
    if (node.additionalProperties === true) {
      return "Record<string, unknown>";
    }

    if (typeof node.additionalProperties === "object") {
      return `Record<string, ${typescriptType(node.additionalProperties)}>`;
    }
  }

  if (node.type === "string" && Array.isArray(node.enum)) {
    return node.enum.map((value) => JSON.stringify(value)).join(" | ");
  }

  switch (node.type) {
    case "boolean":
      return "boolean";
    case "integer":
    case "number":
      return "number";
    case "string":
      return "string";
    default:
      throw new Error(
        `Unsupported TypeScript schema node: ${JSON.stringify(node)}`,
      );
  }
}

function renderRust() {
  const renderedDefinitions = definitions.map(([name, definition]) => {
    if (definition.type !== "object") {
      throw new Error(`Definition ${name} must be an object.`);
    }

    const required = new Set(definition.required ?? []);
    const fields = Object.entries(definition.properties ?? {})
      .sort(([left], [right]) => compareText(left, right))
      .map(([propertyName, propertySchema]) => {
        const fieldName = rustFieldName(propertyName);
        const isRequired = required.has(propertyName);
        const type = rustType(propertySchema);
        const attributes = [];

        if (fieldName.startsWith("r#")) {
          attributes.push(`    #[serde(rename = "${propertyName}")]`);
        }
        if (!isRequired) {
          attributes.push(
            '    #[serde(skip_serializing_if = "Option::is_none")]',
          );
        }

        const fieldType = isRequired ? type : `Option<${type}>`;
        return [...attributes, `    pub ${fieldName}: ${fieldType},`].join(
          "\n",
        );
      });

    return [
      "#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]",
      '#[serde(rename_all = "camelCase", deny_unknown_fields)]',
      `pub struct ${name} {`,
      ...fields,
      "}",
      "",
    ].join("\n");
  });

  return [
    generatedHeader("//"),
    "use std::collections::BTreeMap;",
    "",
    "use serde::{Deserialize, Serialize};",
    "use serde_json::Value;",
    "",
    ...renderedDefinitions,
  ].join("\n");
}

function renderTypeScript() {
  const renderedDefinitions = definitions.map(([name, definition]) => {
    if (definition.type !== "object") {
      throw new Error(`Definition ${name} must be an object.`);
    }

    const required = new Set(definition.required ?? []);
    const fields = Object.entries(definition.properties ?? {})
      .sort(([left], [right]) => compareText(left, right))
      .map(([propertyName, propertySchema]) => {
        const optional = required.has(propertyName) ? "" : "?";
        return `  ${propertyName}${optional}: ${typescriptType(propertySchema)};`;
      });

    return [
      `export interface ${name} {`,
      ...fields,
      "}",
      "",
      `export function parse${name}(`,
      "  input: unknown,",
      "  options: ValidationOptions = {},",
      `): ${name} {`,
      `  return parseWithDefinition<${name}>(\"${name}\", input, options);`,
      "}",
      "",
    ].join("\n");
  });

  return [
    generatedHeader("//"),
    'import { parseWithDefinition, type ValidationOptions } from "../../typescript/validation.js";',
    "",
    ...renderedDefinitions,
  ].join("\n");
}

function renderTypeScriptSchema() {
  return [
    generatedHeader("//"),
    "export const sharedSchema =",
    `${JSON.stringify(schema, null, 2)} as const;`,
    "",
  ].join("\n");
}

const renderedOutputs = new Map([
  [outputs.rust, renderRust()],
  [outputs.typescript, renderTypeScript()],
  [outputs.typescriptSchema, renderTypeScriptSchema()],
]);

let hasStaleOutput = false;
for (const [outputPath, output] of renderedOutputs) {
  const current = existsSync(outputPath)
    ? readFileSync(outputPath, "utf8")
    : null;
  if (current === output) {
    continue;
  }

  if (checkOnly) {
    hasStaleOutput = true;
    process.stderr.write(
      `Generated file is stale: ${relative(repositoryRoot, outputPath)}\n`,
    );
    continue;
  }

  writeFileSync(outputPath, output, "utf8");
  process.stdout.write(`Generated ${relative(repositoryRoot, outputPath)}\n`);
}

if (hasStaleOutput) {
  process.exit(1);
}
